# Server port
server.port=8080

# =============================================
# IMPORTANT: Change these to YOUR details!
# =============================================
app.user.full-name=Akshat Kumar
app.user.dob=24052005
app.user.email=akshat0271.be23@chitkara.edu.in
app.user.roll-number=2310990271

# Application name
spring.application.name=bfhl-api
